# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels: [exclude]
  categories:
    - title: Changes
      labels: ["*"]
    - title: Dependencies
      labels: [dependencies]
