[package]
name = "kopium"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = "0.64.0"
k8s-openapi = { version = "0.13.1", features = ["v1_22"] }
tokio = { version = "1.14.0", features = ["full"] }
anyhow = "1.0.48"
log = "0.4.14"
env_logger = "0.9.0"
serde_json = "1.0.72"
clap = "3.0.0-beta.5"
quote = "1.0.10"
