name: CI
on:
  pull_request:

jobs:
  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.21
          k3d-name: kube
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo build --bin kopium
      # Test a reasonably complicated CRD; promethesurules
      - run: just test-pr
      # Test a fake CRD with multiple versions
      - run: just test-mv
      # Test argocd Application
      - run: just test-argo
      # Test openshift agent crd
      - run: just test-agent
      # Test around documentation in cert-manager certificates
      - run: just test-certmanager
      # Test some linkerd crds
      - run: just test-linkerd-serverauth
      - run: just test-linkerd-server


  rustfmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Run rustfmt
        id: rustfmt
        run: rustfmt +nightly --edition 2018 --check $(find . -type f -iname *.rs)
